export const authGuard = [
  {
    name: 'uploadInventory',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryUploadMaker',
  },
  {
    name: 'upsertInventory',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryUpsert',
  },
  {
    name: 'deleteInventory',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryDelete',
  },
  {
    name: 'upsertInventoryType',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryTypeUpsert',
  },
  {
    name: 'deleteInventoryType',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryTypeDelete',
  },
  {
    name: 'upsertBrandType',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryBrandUpsert',
  },
  {
    name: 'deleteBrandType',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryBrandDelete',
  },
  {
    name: 'favoriteInventory',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryUpsert',
  },
  {
    name: 'recoveryHardDeleted',
    type: 'MUTATION',
    class: 'InventoryResolver',
    scopesName: 'InventoryTrashMaker',
  },
  {
    name: 'getInventoryNames',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getInventory',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getInventories',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getInventoryType',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getInventoryTypes',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getBrandType',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getBrandTypes',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
  {
    name: 'getInventoryAllDeleted',
    type: 'QUERY',
    class: 'InventoryResolver',
    scopesName: 'InventoryMainPage',
  },
]
